In [35]:
import numpy as np
from scipy.linalg import svd

In [26]:
# Create A matrix
A = np.array([[3, 2, 2],
              [2, 3, -2]])

#Matrix A
print("Matrix A:")
print(A)


Matrix A:
[[ 3  2  2]
 [ 2  3 -2]]


In [27]:
# # Find the eigenvalues and eigenvectors
# eigenvalues, eigenvectors = np.linalg.eig(A)

# # Eigenvalues
# print("Eigenvalues:")
# print(eigenvalues)

# # Eigenvectors
# print("Eigenvectors:")
# print(eigenvectors)

In [28]:
# Perform matrix Transpose
A_transpose  = A.T

A_AT = A @ A_transpose
AT_A = A_transpose @ A

In [29]:
# Find the eigenvalues and eigenvectors
eigenvalues1, eigenvectors1 = np.linalg.eig(A_AT)
eigenvalues2, eigenvectors2 = np.linalg.eig(AT_A)


In [30]:
# Eigenvalues
print("Eigenvalues of A_AT :")
print(eigenvalues1)

# Eigenvectors
print("Eigenvectors1 of A_AT :")
print(eigenvectors1)



Eigenvalues of A_AT :
[25.  9.]
Eigenvectors1 of A_AT :
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [31]:
# Eigenvalues
print("Eigenvalues of AT_A :")
print(eigenvalues2)

# Eigenvectors
print("Eigenvectors1 of AT_A :")
print(eigenvectors2)

Eigenvalues of AT_A :
[2.5000000e+01 5.0324328e-15 9.0000000e+00]
Eigenvectors1 of AT_A :
[[-7.07106781e-01 -6.66666667e-01  2.35702260e-01]
 [-7.07106781e-01  6.66666667e-01 -2.35702260e-01]
 [-4.59701721e-17  3.33333333e-01  9.42809042e-01]]


In [34]:
if len(eigenvalues1) <= len(eigenvalues2):
    matrix = []
    for i in range(len(eigenvalues1)):
        row = []
        for j in range(len(eigenvalues1)):
            if(i == j):
                element = (eigenvalues1[i])**1/2
            else:
                element = 0
            row.append(element)
        matrix.append(row)

# Convert the list of lists into a NumPy array
matrix_array = np.array(matrix)

print(matrix_array)

[[12.5  0. ]
 [ 0.   4.5]]


In [36]:
# perform SVD
U, singular, V_transpose = svd(A)
# print different components
print("U: ", U)
print("Singular array", singular)
print("V^{T}", V_transpose)

U:  [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
Singular array [5. 3.]
V^{T} [[-7.07106781e-01 -7.07106781e-01 -5.55111512e-17]
 [-2.35702260e-01  2.35702260e-01 -9.42809042e-01]
 [-6.66666667e-01  6.66666667e-01  3.33333333e-01]]
